apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners-prompt-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prompt-lab-runners-no-permission
  namespace: arc-runners-prompt-lab
automountServiceAccountToken: false
